In [2]:
import os,random
import numpy as np
from random import shuffle


In [3]:
#Mushroom into training_data and test_data
with open('./data/mushroom.txt') as mushroom:
    a = mushroom.read()
    a = a.split('\n')

total_data=[]
for i in a[:-2]:
    b=i.split(',')
    total_data.append(b)

raw_data = np.array(total_data)
np.random.seed(1)
np.random.shuffle(raw_data)



In [4]:
##mushroom feature attribute
#feature={'class':{'edible','poisonous'},'cap-shape':{'bell','conical','convex','flat','knobbed'},'cap-surface..
attributes={}
for i in range(0,len(raw_data[0])):
    features = ['class','cap-shape','cap-surface','cap-color','bruises','odor',
                'gill-attachment','gill-spacing','gill-size','gill-color','stalk-shape','stalk-root',
                'stalk-surface-above','stalk-surface-below','stalk-color-above-r','stalk-color-below-r',
                'veil-type','veil-color','ring-number','ring-type','spore-print-color','population','habitat']
    p=set()

    for j in raw_data:
        p.update(j[i])
    attributes[features[i]]=p
print(attributes)

{'class': {'p', 'e'}, 'cap-shape': {'c', 'x', 'f', 'b', 'k', 's'}, 'cap-surface': {'y', 'f', 'g', 's'}, 'cap-color': {'c', 'y', 'u', 'g', 'p', 'n', 'e', 'w', 'b', 'r'}, 'bruises': {'t', 'f'}, 'odor': {'c', 'l', 'y', 'm', 'n', 'p', 'f', 's', 'a'}, 'gill-attachment': {'f', 'a'}, 'gill-spacing': {'c', 'w'}, 'gill-size': {'n', 'b'}, 'gill-color': {'o', 'r', 'y', 'u', 'g', 'n', 'p', 'k', 'e', 'w', 'b', 'h'}, 'stalk-shape': {'t', 'e'}, 'stalk-root': {'c', 'e', 'b', '?', 'r'}, 'stalk-surface-above': {'y', 'f', 'k', 's'}, 'stalk-surface-below': {'y', 'f', 'k', 's'}, 'stalk-color-above-r': {'c', 'o', 'y', 'g', 'p', 'n', 'e', 'w', 'b'}, 'stalk-color-below-r': {'c', 'o', 'y', 'g', 'n', 'p', 'e', 'w', 'b'}, 'veil-type': {'p'}, 'veil-color': {'n', 'y', 'o', 'w'}, 'ring-number': {'n', 't', 'o'}, 'ring-type': {'l', 'p', 'n', 'f', 'e'}, 'spore-print-color': {'r', 'o', 'b', 'y', 'u', 'n', 'w', 'k', 'h'}, 'population': {'c', 'y', 'n', 'v', 's', 'a'}, 'habitat': {'l', 'd', 'u', 'g', 'm', 'p', 'w'}}


In [5]:
#make_data_into_numbers
List=list(attributes.values())
alphabet_number=[] #각 attribute을 숫자로 나타낸 것 
for i in List:
    Dict={}
    n=0
    for j in list(i):
        Dict[j]=n
        n+=1
    alphabet_number.append(Dict)


In [11]:
#make text_data into list of numbers
xx_data=[] # 트레이닝 데이터의 x벡터(22개 모든 feature에 대해 숫자로 나타냄)

for j in raw_data:
    n=0
    tt=[]
    for t in j:
        tt.append(alphabet_number[n][t])
        n+=1
    xx_data.append(tt)
x = np.array([i[1:] for i in np.array(xx_data)])
y = np.array([i[0] for i in np.array(xx_data)])

[1, 2, 3, 7, 1, 4, 0, 1, 1, 11, 0, 1, 1, 1, 7, 7, 0, 3, 2, 4, 7, 5, 3, 0, 1, 1, 4, 1, 0, 0, 1, 0, 3, 1, 2, 3, 3, 7, 7, 0, 3, 2, 1, 5, 3, 1, 0, 1, 3, 7, 1, 0, 0, 1, 0, 4, 1, 2, 3, 3, 7, 7, 0, 3, 2, 1, 5, 3, 1, 0, 4, 3, 5, 1, 6, 0, 0, 0, 10, 0, 3, 2, 2, 4, 7, 0, 3, 2, 4, 6, 3, 0, 1, 1, 0, 1, 0, 8, 0, 0, 1, 5, 1, 4, 3, 0, 7, 7, 0, 3, 2, 1, 7, 1, 5, 0, 1, 3, 4, 1, 0, 0, 1, 0, 4, 1, 2, 3, 3, 7, 7, 0, 3, 2, 1, 5, 3, 1, 0, 4, 0, 5, 1, 2, 0, 0, 0, 10, 0, 3, 2, 2, 7, 7, 0, 3, 2, 4, 6, 3, 0, 1, 1, 3, 5, 1, 4, 0, 1, 1, 5, 0, 1, 1, 1, 7, 7, 0, 3, 2, 4, 5, 4, 3, 0, 2, 3, 3, 0, 6, 0, 0, 1, 6, 0, 2, 1, 3, 7, 7, 0, 3, 2, 1, 8, 4, 2, 0, 2, 0, 1, 1, 6, 0, 0, 1, 4, 1, 2, 2, 2, 8, 4, 0, 3, 2, 0, 8, 1, 3, 0, 4, 0, 5, 1, 6, 0, 0, 0, 10, 0, 3, 2, 2, 7, 7, 0, 3, 2, 4, 6, 3, 5, 0, 2, 3, 5, 1, 7, 0, 0, 0, 10, 0, 3, 2, 2, 4, 7, 0, 3, 2, 4, 6, 3, 0, 0, 1, 0, 1, 1, 6, 0, 0, 1, 6, 1, 2, 2, 2, 8, 5, 0, 3, 2, 0, 8, 3, 5, 0, 2, 1, 1, 1, 6, 0, 0, 1, 4, 1, 2, 2, 2, 5, 5, 0, 3, 2, 0, 8, 1, 1, 1, 3, 3, 1, 0, 1, 0, 0, 1, 7

In [154]:
import matplotlib.pyplot as plt
import numpy as np

def perceptron(x,y, w=None, eta = 0.05, epochs=100, random_seed = 10): #epochs is how much would you rotate your function
    X = np.c_[np.ones(len(x)),x] #integrate column vector with x in 2order to make a threshold
    if w is None:
        np.random.seed(random_seed)
        w = np.random.random(X.shape[1]) #initial w
    maxlabel, minlabel = y.max(), y.min()   #y.max() is numpy.int32, it can be altered into np.max(y)
    for i in range(epochs):
        for xi,yi in zip(X,y): #zip method is to combine two lists or two vectors into one
            xi = xi.reshape(w.shape) #in case that xi shape and yi shape do not match
            z = np.dot(xi,w.T)
            yhat = np.where(z>=0,maxlabel,minlabel) #where function: if z>=0: return maxlabel, if not: return minlabel
            delta = eta*(yi-yhat)*xi
            w +=delta
    return(np.round(w,2))

In [155]:
%%time
for number in np.arange(10)*0.1:
    if number!= 0:
        num = int(x.shape[0]*round(number,2))
        training_x, test_x = x[:num], x[num:]
        training_y, test_y = y[:num], y[num:]

        weight = perceptron(training_x, training_y)
        print(weight)
        validation = []
        test_x = np.c_[np.ones(len(test_x)),test_x]
        for xi,yi in zip(test_x, test_y):
            z = np.dot(xi,weight.T)
            yhat = np.where(z>=0,1,0)
            if yhat == yi:
                validation.append(1)
            elif yhat != yi:
                validation.append(0)

        percent = round((validation.count(1)/len(validation))*100,2)
        print(str(weight)+'\n'+'트레이닝 데이터 갯수: '+ str(num-1)+'\t'+'확률: '+str(percent)+'\n')

[  3.97  -1.83  -2.72  -0.    -4.25   0.52   4.95  -8.94 -23.83  -0.46
  -5.11  -3.3    6.95   2.76   0.91   0.86   0.72   6.84  -5.53   0.86
  -1.46   0.49  -0.28]
[  3.97  -1.83  -2.72  -0.    -4.25   0.52   4.95  -8.94 -23.83  -0.46
  -5.11  -3.3    6.95   2.76   0.91   0.86   0.72   6.84  -5.53   0.86
  -1.46   0.49  -0.28]
트레이닝 데이터 갯수: 811	확률: 91.88

[ 6.770e+00 -6.300e-01 -1.020e+00  2.500e-01 -5.300e+00 -5.300e-01
  4.200e+00 -8.540e+00 -2.918e+01 -1.000e-02 -8.060e+00 -4.150e+00
  6.800e+00  8.100e-01 -9.000e-02  3.100e-01  7.200e-01  1.039e+01
 -8.180e+00 -1.900e-01 -2.310e+00  2.400e-01 -1.300e-01]
[ 6.770e+00 -6.300e-01 -1.020e+00  2.500e-01 -5.300e+00 -5.300e-01
  4.200e+00 -8.540e+00 -2.918e+01 -1.000e-02 -8.060e+00 -4.150e+00
  6.800e+00  8.100e-01 -9.000e-02  3.100e-01  7.200e-01  1.039e+01
 -8.180e+00 -1.900e-01 -2.310e+00  2.400e-01 -1.300e-01]
트레이닝 데이터 갯수: 1623	확률: 95.89

[ 7.470e+00 -4.300e-01 -1.120e+00 -7.000e-01 -4.800e+00 -1.300e-01
  4.900e+00 -1.144e+01 -3.048e

In [159]:
##another data sample
%%time
data = np.genfromtxt(r'C:/Users/inmmj/Downloads/기계학습5주차/data/joydata.txt')
np.random.seed(2)
np.random.shuffle(data)
print(len(data))
x,y = data[:,:2], data[:,-1]
for number in np.arange(10)*0.1:
    if number!= 0:
        num = int(x.shape[0]*round(number,2))
        training_x, test_x = x[:num], x[num:]
        training_y, test_y = y[:num], y[num:]

        weight = perceptron(training_x, training_y)
        print(weight)
        validation = []
        test_x = np.c_[np.ones(len(test_x)),test_x]
        for xi,yi in zip(test_x, test_y):
            z = np.dot(xi,weight.T)
            yhat = np.where(z>=0,1,0)
            if yhat == yi:
                validation.append(1)
            elif yhat != yi:
                validation.append(0)

        percent = round((validation.count(1)/len(validation))*100,2)
        print(str(weight)+'\n'+'트레이닝 데이터 갯수: '+ str(num-1)+'\t'+'확률: '+str(percent)+'\n')

100
[0.72 0.17 0.69]
[0.72 0.17 0.69]
트레이닝 데이터 갯수: 9	확률: 87.78

[0.12 0.01 0.16]
[0.12 0.01 0.16]
트레이닝 데이터 갯수: 19	확률: 88.75

[0.12 0.12 0.14]
[0.12 0.12 0.14]
트레이닝 데이터 갯수: 29	확률: 94.29

[0.12 0.12 0.14]
[0.12 0.12 0.14]
트레이닝 데이터 갯수: 39	확률: 93.33

[0.07 0.08 0.08]
[0.07 0.08 0.08]
트레이닝 데이터 갯수: 49	확률: 96.0

[0.02 0.06 0.13]
[0.02 0.06 0.13]
트레이닝 데이터 갯수: 59	확률: 95.0

[0.02 0.09 0.17]
[0.02 0.09 0.17]
트레이닝 데이터 갯수: 69	확률: 96.67

[-0.03  0.05  0.14]
[-0.03  0.05  0.14]
트레이닝 데이터 갯수: 79	확률: 100.0

[-0.03  0.05  0.14]
[-0.03  0.05  0.14]
트레이닝 데이터 갯수: 89	확률: 100.0

Wall time: 746 ms
